# Generated by Django 6.0.4 on 2026-04-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=255, verbose_name='Nome Fantasia')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('categoria', models.CharField(choices=[('hospedagem', 'Hospedagem (Hotel/Pousada)'), ('cinema', 'Cinema'), ('eventos', 'Shows & Eventos'), ('parques', 'Parques e Atrações')], max_length=20, verbose_name='Categoria Principal')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='empresas/banners/')),
                ('cor_primaria', models.CharField(default='#1e3a8a', max_length=7, verbose_name='Cor da Marca (Hex)')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('email_contato', models.EmailField(max_length=254, verbose_name='E-mail de Contato')),
                ('telefone_contato', models.CharField(max_length=20, verbose_name='Telefone / WhatsApp')),
                ('ativa', models.BooleanField(default=True)),
                ('destaque', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='PlataformaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_site', models.CharField(default='Naviê Vibe', max_length=100)),
                ('google_maps_key', models.CharField(blank=True, max_length=255, verbose_name='Google Maps API Key')),
                ('cloudinary_url', models.CharField(blank=True, max_length=255, verbose_name='Cloudinary URL')),
                ('gateway_ativo', models.CharField(choices=[('stripe', 'Stripe'), ('mercado_pago', 'Mercado Pago')], default='stripe', max_length=20)),
                ('payment_public_key', models.CharField(blank=True, max_length=255, verbose_name='Chave Pública de Pagamento')),
                ('payment_secret_key', models.CharField(blank=True, max_length=255, verbose_name='Chave Secreta de Pagamento')),
                ('taxa_hospedagem', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Taxa Hospedagem (%)')),
                ('taxa_cinema', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Taxa Cinema (%)')),
                ('taxa_eventos', models.DecimalField(decimal_places=2, default=12.0, max_digits=5, verbose_name='Taxa Eventos (%)')),
                ('taxa_parques', models.DecimalField(decimal_places=2, default=8.0, max_digits=5, verbose_name='Taxa Parques (%)')),
            ],
            options={
                'verbose_name': 'Configuração da Plataforma',
                'verbose_name_plural': 'Configurações da Plataforma',
            },
        ),
    ]
