# Generated by Django 6.0.4 on 2026-05-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plataformaconfig',
            name='taxa_gateway_percentual',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Percentual cobrado pelo gateway de pagamento (ex: 3.00 para 3%).', max_digits=4, verbose_name='Taxa de Cobrança do Gateway (%)'),
        ),
    ]
