# Generated by Django 6.0.4 on 2026-05-24 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0004_alter_hotel_empresa_alter_reserva_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParceiroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('proprietario', 'Proprietário'), ('gerente', 'Gerente'), ('portaria', 'Portaria / Recepção'), ('camareira', 'Camareira / Limpeza'), ('manutencao', 'Manutenção')], default='portaria', max_length=30)),
                ('cpf', models.CharField(blank=True, help_text='Formato: 000.000.000-00', max_length=14, null=True, unique=True)),
                ('ativo', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='equipe', to='hoteis.hotel')),
                ('user', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_parceiro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
