# Generated by Django 6.0.4 on 2026-05-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0006_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='cor_primaria',
            field=models.CharField(default='#f97316', help_text='Cor primária em formato Hexadecimal (ex: #f97316)', max_length=7),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hero_tipo',
            field=models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo')], default='imagem', help_text='Tipo de mídia a ser exibida no cabeçalho/Hero do site', max_length=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hero_video',
            field=models.FileField(blank=True, help_text='Vídeo curto em loop (MP4 de até 8MB)', null=True, upload_to='hoteis/videos/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada geográfica de latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada geográfica de longitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp de contato do hotel', max_length=20, null=True),
        ),
    ]
