# Generated by Django 6.0.4 on 2026-05-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0007_hotel_cor_primaria_hotel_hero_tipo_hotel_hero_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='foto_fundo',
            field=models.ImageField(blank=True, help_text='Imagem de fundo para o modo Glassmorphism', null=True, upload_to='hoteis/fundos/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo oficial da pousada', null=True, upload_to='hoteis/logos/'),
        ),
    ]
