# Generated by Django 6.0.4 on 2026-05-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0009_hotel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='capacidade_pessoas',
            field=models.IntegerField(default=2, help_text='Capacidade de hóspedes'),
        ),
        migrations.AddField(
            model_name='quarto',
            name='comodidades',
            field=models.CharField(blank=True, default='', help_text='Comodidades (ex: Ar Condicionado, Wi-Fi)', max_length=255),
        ),
        migrations.AddField(
            model_name='quarto',
            name='dias_minimos_desconto',
            field=models.IntegerField(default=3, help_text='Mínimo de dias para ativar desconto'),
        ),
        migrations.AddField(
            model_name='quarto',
            name='percentual_desconto',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Desconto em percentual (ex: 10.00 para 10%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='quarto',
            name='seo_descricao',
            field=models.TextField(blank=True, help_text='Descrição customizada para buscadores/IA', null=True),
        ),
        migrations.AddField(
            model_name='quarto',
            name='seo_titulo',
            field=models.CharField(blank=True, help_text='Título customizado para buscadores/IA', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='quarto',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Categorização (ex: Família, Romântico)', max_length=255),
        ),
        migrations.AddField(
            model_name='quarto',
            name='tem_desconto_multidias',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quarto',
            name='video_url',
            field=models.CharField(blank=True, help_text='Link para vídeo MP4 ou embed', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
