# Generated by Django 6.0.4 on 2026-05-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0010_quarto_capacidade_pessoas_quarto_comodidades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='video_arquivo',
            field=models.FileField(blank=True, help_text='Arquivo de vídeo local do tour', null=True, upload_to='quartos/videos/'),
        ),
    ]
