# Generated by Django 6.0.4 on 2026-05-25 (manual split for data migration)

import unicodedata
from django.db import migrations, models
from django.utils.text import slugify


def _normalizar_slug(texto):
    nfkd = unicodedata.normalize('NFKD', texto)
    ascii_str = nfkd.encode('ascii', 'ignore').decode('ascii')
    return slugify(ascii_str)


def popular_slugs(apps, schema_editor):
    """Gera slugs únicos por hotel para todos os quartos existentes."""
    Quarto = apps.get_model('hoteis', 'Quarto')
    db = schema_editor.connection.alias

    # Agrupa quartos por hotel para garantir unicidade dentro de cada hotel
    from collections import defaultdict
    por_hotel = defaultdict(list)
    for q in Quarto.objects.using(db).all():
        por_hotel[q.hotel_id].append(q)

    for hotel_id, quartos in por_hotel.items():
        slugs_usados = set()
        for q in quartos:
            base = _normalizar_slug(q.nome) or f'acomodacao-{q.pk}'
            candidato = base
            num = 2
            while candidato in slugs_usados:
                candidato = f'{base}-{num}'
                num += 1
            slugs_usados.add(candidato)
            q.slug = candidato
            Quarto.objects.using(db).filter(pk=q.pk).update(slug=candidato)


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0011_quarto_video_arquivo'),
    ]

    operations = [
        # Step 1: Adiciona coluna sem constraint
        migrations.AddField(
            model_name='quarto',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigável gerada automaticamente pelo nome', max_length=180),
        ),
        # Step 2: Popula slugs únicos para registros existentes
        migrations.RunPython(popular_slugs, migrations.RunPython.noop),
        # Step 3: Aplica unique_together agora que não há duplicatas
        migrations.AlterUniqueTogether(
            name='quarto',
            unique_together={('hotel', 'slug')},
        ),
    ]
