# Generated by Django 6.0.4 on 2026-05-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0012_quarto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloqueioquarto',
            name='data_fim',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='bloqueioquarto',
            name='data_inicio',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], db_index=True, default='ativo', max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_checkin',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_checkout',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], db_index=True, default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data_vencimento',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('todo', 'A Fazer'), ('doing', 'Em Progresso'), ('done', 'Concluído')], db_index=True, default='todo', max_length=10),
        ),
        migrations.AlterField(
            model_name='unidadequarto',
            name='ativa',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
