# Generated by Django 6.0.4 on 2026-05-26 20:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0014_reserva_canal_venda_reserva_checkin_realizado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeiculoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('cor', models.CharField(blank=True, max_length=50)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='veiculo', to='hoteis.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='HospedeReserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('rg', models.CharField(blank=True, max_length=50)),
                ('nacionalidade', models.CharField(default='Brasileira', max_length=100)),
                ('profissao', models.CharField(blank=True, max_length=100)),
                ('endereco', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospedes', to='hoteis.reserva')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('reserva', 'ordem')},
            },
        ),
    ]
