# Generated by Django 6.0.4 on 2026-05-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0015_veiculoreserva_hospedereserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='ganho_liquido_plataforma',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ganho Líquido Naviê'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='repasse_parceiro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Repasse Líquido ao Parceiro'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='taxa_gateway',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Taxa Gateway Absorvida'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='taxa_servico_plataforma',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Taxa de Serviço Naviê'),
        ),
    ]
