# Generated by Django 6.0.4 on 2026-04-17 13:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('termos-parceria', 'Termos de Parceria'), ('politica-privacidade', 'Política de Privacidade')], max_length=60, unique=True, verbose_name='Identificador')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('conteudo', models.TextField(help_text='Pode usar HTML básico: &lt;h2&gt;, &lt;p&gt;, &lt;ul&gt;, &lt;strong&gt;, etc.', verbose_name='Conteúdo (HTML)')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Documento Legal',
                'verbose_name_plural': 'Documentos Legais',
                'db_table': 'parceiros_documento',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=200, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('tipo_empresa', models.CharField(choices=[('hotel_pousada', 'Hotel / Pousada'), ('cinema', 'Cinema'), ('casa_shows', 'Casa de Shows'), ('produtor_eventos', 'Produtor de Eventos'), ('restaurante', 'Restaurante / Gastronomia'), ('parque_turismo', 'Parque / Turismo'), ('outro', 'Outro')], max_length=30, verbose_name='Tipo de Negócio')),
                ('site', models.URLField(blank=True, verbose_name='Site Institucional')),
                ('instagram', models.CharField(blank=True, max_length=200, verbose_name='Instagram / Redes Sociais')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('endereco', models.CharField(max_length=300, verbose_name='Endereço (Rua/Av)')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('responsavel_nome', models.CharField(max_length=150, verbose_name='Nome do Responsável')),
                ('responsavel_cargo', models.CharField(max_length=100, verbose_name='Cargo / Função')),
                ('responsavel_email', models.EmailField(max_length=254, verbose_name='E-mail Corporativo')),
                ('responsavel_telefone', models.CharField(max_length=20, verbose_name='Telefone / WhatsApp')),
                ('descricao_negocio', models.TextField(help_text='O que a empresa oferece, capacidade, diferenciais...', verbose_name='Descrição do Negócio')),
                ('capacidade', models.CharField(blank=True, help_text='Ex: 20 quartos, 300 lugares, etc.', max_length=200, verbose_name='Capacidade / Tamanho')),
                ('como_soube', models.CharField(blank=True, max_length=200, verbose_name='Como ficou sabendo do Naviê?')),
                ('aceite_termos', models.BooleanField(default=False, verbose_name='Aceita Termos de Parceria')),
                ('aceite_privacidade', models.BooleanField(default=False, verbose_name='Aceita Política de Privacidade')),
                ('autoriza_contato', models.BooleanField(default=False, verbose_name='Autoriza contato da equipe Naviê')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_contato', 'Em Contato'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('aguardando_doc', 'Aguardando Documentação')], default='pendente', max_length=20, verbose_name='Status')),
                ('notas_internas', models.TextField(blank=True, help_text='Observações da equipe Naviê (não visível ao solicitante)', verbose_name='Notas Internas')),
                ('data_solicitacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Solicitação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('atendido_por', models.CharField(blank=True, help_text='Nome do membro da equipe Naviê responsável', max_length=100, verbose_name='Atendido por')),
            ],
            options={
                'verbose_name': 'Solicitação de Empresa',
                'verbose_name_plural': 'Solicitações de Empresas',
                'db_table': 'parceiros_solicitacao_empresa',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
