# Generated by Django 6.0.4 on 2026-05-22 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(help_text='Cadastro de Pessoas Físicas do cliente. Formato: 000.000.000-00', max_length=14, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(help_text='Número de telefone principal do cliente. Formato: (00) 00000-0000', max_length=20, verbose_name='Telefone / WhatsApp')),
                ('cep', models.CharField(help_text='Código de Endereçamento Postal do local de residência. Formato: 00000-000', max_length=9, verbose_name='CEP')),
                ('endereco', models.CharField(help_text='Nome da rua/avenida e logradouro.', max_length=255, verbose_name='Endereço')),
                ('numero', models.CharField(help_text='Número residencial, comercial ou complemento.', max_length=20, verbose_name='Número')),
                ('bairro', models.CharField(help_text='Bairro correspondente do endereço.', max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(help_text='Cidade de residência do cliente.', max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(help_text='Sigla de duas letras correspondente ao estado brasileiro (ex: CE).', max_length=2, verbose_name='Estado (UF)')),
                ('aceite_termos', models.BooleanField(default=False, help_text='Define se o cliente manifestou concordância ativa com os Termos de Uso do Naviê Vibe.', verbose_name='Aceita Termos de Uso')),
                ('data_aceite_termos', models.DateTimeField(blank=True, help_text='Carimbo de data/hora oficial e imutável registrando quando o aceite ocorreu.', null=True, verbose_name='Data de Aceite')),
                ('registro_ip', models.GenericIPAddressField(blank=True, help_text='Endereço IP (IPv4 ou IPv6) de onde partiu a requisição de cadastro.', null=True, verbose_name='IP do Registro')),
                ('registro_user_agent', models.TextField(blank=True, help_text='Assinatura técnica do navegador e sistema operacional do cliente coletada no cadastro.', null=True, verbose_name='User Agent do Registro')),
                ('user', models.OneToOneField(help_text='O usuário de sistema Django proprietário deste perfil.', on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Cliente',
                'verbose_name_plural': 'Perfis de Clientes',
            },
        ),
    ]
