# Generated by Django 6.0.4 on 2026-05-24 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('hoteis', '0004_alter_hotel_empresa_alter_reserva_id_and_more'),
        ('parques', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parque',
            name='empresa',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_parque', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='parque',
            name='hospedagens_vinculadas',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='parques_donos', to='hoteis.hotel'),
        ),
    ]
