# Generated by Django 6.0.4 on 2026-05-26 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_plataformaconfig_taxa_gateway_percentual'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraTaxa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('hospedagem', 'Hospedagem (Hotel/Pousada)'), ('cinema', 'Cinema'), ('eventos', 'Shows & Eventos'), ('parques', 'Parques e Atrações')], default='hospedagem', max_length=20, verbose_name='Categoria Principal')),
                ('valor_minimo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Mínimo (R$)')),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Máximo (R$)')),
                ('tipo_taxa', models.CharField(choices=[('percentual', 'Percentual (%)'), ('fixa', 'Fixa (R$)')], default='percentual', max_length=15, verbose_name='Tipo de Taxa')),
                ('valor', models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Valor da Taxa')),
                ('cobranca_por_diaria', models.BooleanField(default=False, help_text='Apenas para Hospedagem: se ativado, multiplica o valor fixo pela quantidade de noites.', verbose_name='Cobrança por Diária')),
                ('ordem_prioridade', models.IntegerField(default=0, help_text='Prioridades mais altas rodam primeiro (ex: parceiro = 10, tiers = 5, geral = 0).', verbose_name='Ordem de Prioridade')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regras_taxa', to='core.empresa', verbose_name='Parceiro / Empresa')),
            ],
            options={
                'verbose_name': 'Regra de Taxa',
                'verbose_name_plural': 'Regras de Taxas',
                'ordering': ['-ordem_prioridade', 'valor_minimo'],
            },
        ),
    ]
